### ISSUE TITLE
Cannot determine if CacheLoader can bulk load

### ISSUE THREAD

**Issue by xstefank** [xstefank/wildfly-github-bot#138]
```
2023-08-15 06:14:38,803 WARNING [com.git.ben.caf.cac.LocalLoadingCache] (main) Cannot determine if CacheLoader can bulk load: java.lang.NoSuchMethodException: io.quarkiverse.githubapp.runtime.github.GitHubService$CreateInstallationToken.loadAll(java.util.Set)
	at java.base@17.0.8/java.lang.Class.checkMethod(DynamicHub.java:1038)
	at java.base@17.0.8/java.lang.Class.getMethod(DynamicHub.java:1023)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.hasLoadAll(LocalLoadingCache.java:220)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.newBulkMappingFunction(LocalLoadingCache.java:198)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.<init>(BoundedLocalCache.java:4436)
	at com.github.benmanes.caffeine.cache.Caffeine.build(Caffeine.java:1076)
	at io.quarkiverse.githubapp.runtime.github.GitHubService.<init>(GitHubService.java:69)
	at io.quarkiverse.githubapp.runtime.github.GitHubService_Bean.doCreate(Unknown Source)
	at io.quarkiverse.githubapp.runtime.github.GitHubService_Bean.create(Unknown Source)
	at io.quarkiverse.githubapp.runtime.github.GitHubService_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
	at io.quarkiverse.githubapp.runtime.github.GitHubService_ClientProxy.arc$delegate(Unknown Source)
	at io.quarkiverse.githubapp.runtime.github.GitHubService_ClientProxy.getApplicationClient(Unknown Source)
	at io.xstefank.wildfly.bot.LifecycleProcessor.onStart(LifecycleProcessor.java:73)
	at io.xstefank.wildfly.bot.LifecycleProcessor_Observer_onStart_175afe88331b177e391525f2c82e29ae610f722a.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:346)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:328)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:155)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:106)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
```

**Comment by xstefank** [comment]
@The-Huginn
